### ISSUE TITLE
[Suggestion] Custom Hotkey

### ISSUE THREAD

**Issue by Mysticql** [zSynctic/AutoClicker#2]
Hey I was wondering if a custom hotkey could be chosen to enable and disable the clicker. Basically within the GUI you'd be able to bind a key for the normal click and the hold click.

and maybe even the possibility of leaving one unbinded if you only use one of them (Ex. You can press backspace or something to have no keybind)

**Comment by Mysticql** [comment]
Also I've had issues where sometimes the autoclicker does not disable when you press the F6 key so it's a struggle trying to close the clicker lol. Not sure what causes it though.

I only use the hold click so not sure if it applies to the regular clicking also.

**Comment by zSynctic** [comment]
Yeah I'm thinking of adding a custom hotkey option but I'm still working on other things. I will try fix that issue when I have time thanks.

**Comment by zSynctic** [comment]
Hey! Yes — Settings getting saved from last session, hotkey and settings customization and background (inactive) window clicking has now been fully implemented.

It’s available in ZClicker Pro along with click position and customizable hotkeys.

I focused on making it simple and reliable compared to other autoclickers.

You can check it out here:
https://zclicker.com/
