### ISSUE TITLE
Hey! Is there a specific window clicking functionality planned?

### ISSUE THREAD

**Issue by dasiuk** [zSynctic/AutoClicker#4]
I need an autoclicker that can click a specific keyboard key every 20 seconds in a specific window, and this one got 2/3 for me. So I wanted to ask if there will be a "target window" clicking functionality?

**Comment by zSynctic** [comment]
Thanks for the idea. I wasn't planning on doing this at first since I thought it was impossible to do that with the python programming language. But I think I found a solution I will try to add it in the next updates if I'm able to do it.

**Comment by dasiuk** [comment]
Oh man, sounds great! I'll be waiting and hoping

**Comment by zSynctic** [comment]
Hopefully I will be able to do it. If I do it, it will probably not be apart of the next update. The next update is almost ready idk if I should publish the next update first or should I try adding this to it then publishing it but that might take time. Also I'm currently busy with some tests and stuff

**Comment by dasiuk** [comment]
Oke, no problems. If you need help you can tell me

**Comment by zSynctic** [comment]
ok, thanks btw just noting probably in the next update I will change the name of the autoclicker since this name is so common and now the program is getting popular so it has to be special

**Comment by dasiuk** [comment]
Sure, as you wish

**Comment by dasiuk** [comment]
Oh! Btw, since I tried many-many autoclickers at this point, I've noticed something worth noting. In few autoclickers that work in minimized windows (both clicker and game are minimized) there is something called PS / 2 keyboard emulation. As I understood it, they use some kind of software keyboard emulation tricks to make virtual clicks with non-existent emulated keyboard. Maybe that will help

**Comment by zSynctic** [comment]
Oh thanks. I already got an Idea in my mind it probably does the same thing u just explained hopefully it will work but I guess for this Idea to work I will have to put a coordinate option first like the other autoclickers if you know what I mean

**Comment by dasiuk** [comment]
Hey, I wanted to ask how's the progress going on specific window clicking

**Comment by dasiuk** [comment]
Oke, I will be waiting patiently

**Comment by zSynctic** [comment]
Thanks man

**Comment by dasiuk** [comment]
Hey, it's been almost 2 month since I last asked, and 4+ month since last update. So I just wanted to ask last time if there will be unfocused window clicking functionality added

**Comment by zSynctic** [comment]
Yeah hopefully I'm working on it and testing it, I was working on other projects so yeah hopefully it will be out soon

**Comment by dasiuk** [comment]
> Yeah hopefully I'm working on it and testing it, I was working on other projects so yeah hopefully it will be out soon

pog

**Comment by dasiuk** [comment]
Hey, I accidentally remembered about this thread here. Just wanna ask if clicking in inactive window was ever implemented

**Comment by zSynctic** [comment]
Hey! Yes — background (inactive) window clicking has now been fully implemented.

It’s available in ZClicker Pro along with click position and customizable hotkeys.

I focused on making it simple and reliable compared to other autoclickers.

You can check it out here:
https://zclicker.com

**Comment by dasiuk** [comment]
Hey. Is PRO a one-time payment? Will it be supported further?

**Comment by zSynctic** [comment]
Yes its a one time payment and yes Im planning on hopefully continuing support on it and maybe still add some features

**Comment by dasiuk** [comment]
Got it, thank you

**Comment by dasiuk** [comment]
<img width="415" height="102" alt="Image" src="https://github.com/user-attachments/assets/b2312d6f-54bf-4ac5-b9c5-ac448a4a0a01" />
no idea, will try later maybe

**Comment by zSynctic** [comment]
Alright, the issue seems to not be from my side you should check your bank, anyways thanks for considering buying it and I made sure its cheap so its available to everyone and ngl its one way to support me and my journey so thanks alot and if you ever have any suggestions and additions to the pro version please be sure to let me know

**Comment by dasiuk** [comment]
Keyboard clicking maybe?

**Comment by zSynctic** [comment]
Already available

**Comment by zSynctic** [comment]
For the keyboard clicking instead of choosing from the menu you just type the letter you want to press and start autoclicking also added hotkeys and hotkey customization and other settings in the pro version which save for next time use

**Comment by zSynctic** [comment]
Did you try again?
